apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sohila12/netflix-clone-devsecops-mirror.git
    targetRevision: main
    path: Kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: netflix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
